SuperAdmin.WebUI/Areas/AdminArea/Controllers/MemberOperaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SuperAdmin.datamodel;
using SuperAdmin.DataBLL;
using SuperAdmin.WebUI.Areas.AdminArea.Models;
using SuperAdmin.WebUI.Models;
using SuperAdmin.WebUI.Controllers;

namespace SuperAdmin.WebUI.Areas.AdminArea.Controllers
{
    public class MemberOperaController : Controller
    {
        //后台管理会员页面
        // GET: /AdminArea/MemberOpera/
        MemberOperaBll bll = new MemberOperaBll();
        public ActionResult Index()
        {
            MemberViewModel model = new MemberViewModel();
            model.memberlist = bll.GetAllMemberInfo();
            ViewBag.PageTitle = "会员管理";
            return View(model);
        }
        /// <summary>
        /// 审核会员
        /// </summary>
        /// <param name="mid"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult checkmember(int mid)
        {
            if (mid > 0)
            {
                SessionLoginModel user = Session[AppContext.SESSION_LOGIN_NAME] as SessionLoginModel;
                MemberInfoModel model = new MemberInfoModel();
                model.ID = mid;
                model.CheckUserID = user.User.ID;
                model.CheckUserName = user.User.UserName;
                int rowcount = bll.CheckMemberStatus(model);
                if (rowcount > 0)
                {
                    return Json("1");
                }
                else
                {
                    return Json("0");
                }
            }
            return Json("0");
        }
        /// <summary>
        /// 禁用会员
        /// </summary>
        /// <param name="mid"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult delmember(int mid)
        {
            if (mid > 0)
            {                
                int rowcount = bll.DelMember(mid);
                if (rowcount > 0)
                {
                    return Json("1");
                }
                else
                {
                    return Json("0");
                }
            }
            return Json("0");
        }
    }
}

SuperAdmin.WebUI/Areas/AdminArea/Views/MemberOpera/Index.cshtml
@model SuperAdmin.WebUI.Areas.AdminArea.Models.MemberViewModel
@{
    Layout = "~/Views/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div id="content" class="col-lg-12">
            <!-- PAGE HEADER-->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-header">
                        <!-- BREADCRUMBS -->
                        <ul class="breadcrumb">
                            <li>
                                <i class="fa fa-home"></i>
                                <a href="index.html">Home</a>
                            </li>
                            <li>
                                <a href="#">会员管理</a>
                            </li>
                            <li>会员管理</li>
                        </ul>
                        <!-- /BREADCRUMBS -->
                        <div class="clearfix">
                            <h3 class="content-title pull-left">会员管理</h3>
                        </div>
                        <div class="description"></div>
                    </div>
                </div>
            </div>
            <!-- /PAGE HEADER -->
            <div class="row">
                <div class="col-sm-11">
                    <div class="btn-group hidden-xs pull-right invoice-btn-group">
                        <p class="btn-toolbar">
                            <a class="btn btn-primary" data-toggle="modal" href="#" id="addnew"><i class="fa fa-search"></i>&nbsp;查询条件预留</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row" id="tabdiv">
                        <table class="table table-striped table-bordered" id="menutab">
                            <thead>
                                <tr>
                                    <th class="text-center">会员编号</th>
                                    <th class="text-center">会员名称</th>
                                    <th class="text-center">注册时间</th>
                                    <th class="text-center">会员等级</th>
                                    <th class="text-center">会员邮箱</th>
                                    <th class="text-center">最后登录时间</th>
                                    <th class="text-center">审  核  人</th>
                                    <th class="text-center">状        态</th>
                                    <th class="text-center">编        辑</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.memberlist)
                                {
                                    <tr id="tr@(item.ID)" class="text-center">
                                        <td>@item.ID</td>
                                        <td>@item.MemberName</td>
                                        <td>@item.MRegisterTime</td>
                                        <td name="@item.MGrade">@item.MGradeName</td>
                                        <td>@item.MEmail</td>
                                        <td>@(item.LastLoginTime==DateTime.MinValue?"":item.LastLoginTime.ToString("yyyy-MM-dd HH:mm:ss"))</td>
                                        <td>@item.CheckUserName</td>
                                        <td name="@(item.MStatus)">
                                            @item.MstatusName
                                        </td>
                                        <td>
                                            <p class="btn-toolbar">
                                                <button class="btn btn-success" data-toggle="modal"><i class="fa fa-pencil-square-o"></i>&nbsp;查看</button>
                                                <button class="btn btn-warning" data-toggle="modal" onclick="checkm(@item.ID)" ><i class="fa fa-pencil-square-o"></i>&nbsp;审核</button>
                                                <button class="btn btn-danger" data-toggle="modal" onclick="delm(@item.ID)" ><i class="fa fa-times-circle"></i>&nbsp; 禁 用</button>
                                            </p>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section mycss{
    <link rel="stylesheet" href="@Url.Content("/js/gritter/css/jquery.gritter.css")">
}
@section scriptfiles{
    <script src="@Url.Content("/js/gritter/js/jquery.gritter.min.js")"></script>
}
@section myscript{
    <script type="text/javascript">
        $(function () {
            App.init(); //Initialise plugins and elements
        });
        function checkm(mid) {
            $.ajax({
                url: '@Url.Action("checkmember", "MemberOpera", new { area = "AdminArea" })',
                dataType: 'Json',
                data: { 'mid': mid },
                type: 'POST',
                success: function (data) {
                    var str = ''; var img = '';
                    if (data == '1') {
                        var id = $("#tr" + mid + " td:nth-child(8)").attr("name");
                        if (id == '100') {
                            $("#tr" + mid + " td:nth-child(8)").attr("name", "200");
                            $("#tr" + mid + " td:nth-child(8)").html("审核通过");
                        }
                        else {
                            $("#tr" + mid + " td:nth-child(8)").attr("name", "100");
                            $("#tr" + mid + " td:nth-child(8)").html("待审核");
                        }
                        str = "操作成功！";
                        img = '/img/gritter/success.jpg';
                    }
                    else {
                        str = "操作失败！";
                        img = '/img/gritter/error.png';
                    }
                    setTimeout(function () {
                        var unique_id = $.gritter.add({
                            // (string | mandatory) the heading of the notification
                            title: str,
                            // (string | mandatory) the text inside the notification
                            text: '',
                            // (string | optional) the image to display on the left
                            image: img,
                            // (bool | optional) if you want it to fade out on its own or just sit there
                            sticky: true,
                            // (int | optional) the time you want it to be alive for before fading out
                            time: '',
                            // (string | optional) the class name you want to apply to that specific message
                            class_name: 'my-sticky-class'
                        });
                        // You can have it return a unique id, this can be used to manually remove it later using
                        setTimeout(function () {
                            $.gritter.remove(unique_id, {
                                fade: true,
                                speed: 'slow'
                            });
                        }, 3000);
                    }, 0);
                }
            });
        }
        function delm(mid) {
            $.ajax({
                url: '@Url.Action("delmember", "MemberOpera", new { area = "AdminArea" })',
                dataType: 'Json',
                data: { 'mid': mid },
                type: 'POST',
                success: function (data) {
                    var str = ''; var img = '';
                    if (data == '1') {
                        $("#tr" + mid + " td:nth-child(8)").attr("name", "300");
                        $("#tr" + mid + " td:nth-child(8)").html("账户禁用");
                        str = "操作成功！";
                        img = '/img/gritter/success.jpg';
                    }
                    else {
                        str = "操作失败！";
                        img = '/img/gritter/error.png';
                    }
                    setTimeout(function () {
                        var unique_id = $.gritter.add({
                            // (string | mandatory) the heading of the notification
                            title: str,
                            // (string | mandatory) the text inside the notification
                            text: '',
                            // (string | optional) the image to display on the left
                            image: img,
                            // (bool | optional) if you want it to fade out on its own or just sit there
                            sticky: true,
                            // (int | optional) the time you want it to be alive for before fading out
                            time: '',
                            // (string | optional) the class name you want to apply to that specific message
                            class_name: 'my-sticky-class'
                        });
                        // You can have it return a unique id, this can be used to manually remove it later using
                        setTimeout(function () {
                            $.gritter.remove(unique_id, {
                                fade: true,
                                speed: 'slow'
                            });
                        }, 3000);
                    }, 0);
                }
            });
        }
    </script>
}